server:
  port: 8080

spring:
  main:
    banner-mode: "off"
  profiles:
    active: "local"
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
        - ${ADDITIONAL_STATIC_LOCATION:classpath:/additional-static/} # can be set to file:/opt/static/ for serving contents outside of jar

springdoc:
  api-docs:
    path: "/api-docs"
    enabled: false
  swagger-ui:
    path: "/swagger-ui.html"

management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: health,info
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
      git:
        mode: "full"

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m %wEx %n'